### ISSUE TITLE
update to latest version

### ISSUE THREAD

**Issue by DOFfactory** [mikenye/docker-picard#1]
Just noticed your docker version is on 2.1.2 and there is a newer 2.2.3. Any chance of updating? Maybe automate it within the docker?

**Comment by mikenye** [comment]
Absolutely. It has been on my todo list to automate this. Stay tuned...

**Comment by mikenye** [comment]
2.2.3 is now available on Docker Hub. From this point forward a new docker image should be pushed with 24 hours of it being available on `ppa:musicbrainz-developers/stable`.
