### ISSUE TITLE
Update to v2.3.2

### ISSUE THREAD

**Issue by kullervo610** [mikenye/docker-picard#15]
Picard version 2.3.2 is out, kindly asking updated version when you have time.
https://picard.musicbrainz.org/changelog/

Off topic related to a already closed issue (no action needed for my comment below)
Thanks about that browser intergration it works great :) with chromium. Firefox crashes were likely because of lack of shared memory i.e. size of /dev/shm is too small within a container.

**Comment by kullervo610** [comment]
That was extremely quick! Thanks a lot !!! I already took v2.3.2 into production 👍

**Comment by mikenye** [comment]
No problems. New versions should be built automatically, however my build platform was caching the old image! It should be fixed from this point onwards. Cheers!
