### ISSUE TITLE
Set VNC resolution?

### ISSUE THREAD

**Issue by NoLooseEnds** [mikenye/docker-picard#18]
Hi, appreciate you putting together this!

I was wondering if it's an easy way to change the resolution of VNC? I would like to set a higher resolution. 

I did try to set `-geometry ####x####` and `-scale 0.9x0.75`, but it did not achieve what I wanted.

**Comment by mikenye** [comment]
Hi @NoLooseEnds,

The container supports the following environment variables:

| Variable       | Description                                  | Default |
|----------------|----------------------------------------------|---------|
|`DISPLAY_WIDTH`| Width (in pixels) of the application's window. | `1280` |
|`DISPLAY_HEIGHT`| Height (in pixels) of the application's window. | `768` |

Add those to your container’s `docker run` or `docker-compose.yml` and set the values to your liking. 

Let me know how you go.

**Comment by NoLooseEnds** [comment]
Thanks for the quick response. 👍 

I did go through the documentation and environment variables, but I'm apparently blind. 👀 

Sorry to have bothered you with this.

**Comment by mikenye** [comment]
No bother! :-)
