### ISSUE TITLE
Japanese fonts not displayed correctly

### ISSUE THREAD

**Issue by kullervo610** [mikenye/docker-picard#2]
Been trying out mikenye/picard:latest for couple of days. Big thanks putting it together! An issue I am facing that Japanese fonts are not correctly displayed, neither in folder/file names nor within tags. I have enabled Japanese fonts with ENABLE_CJK_FONT variable. An issue is reprodusable i.e. it happens every time when I try to tag music with Japanese text.

**Comment by mikenye** [comment]
Hi @kullervo610,
You’re most welcome! I don’t know much (any) Japanese music, so if you’re able to link me to an album on freedb or another online database, that would help me troubleshoot. 
Thanks!

**Comment by kullervo610** [comment]
I am a bit struggling to find you a good sample on-line. I keep on looking but this may take a bit time. Once more thanks! It is great that someone put effort to containarize Picard.

**Comment by mikenye** [comment]
You're very welcome! I spoke to my wife about this, and she reminded me that she has the Studio Ghibli box set soundtrack in her CD collection, so I was able to replicate your issue! It's a good thing I married her.

I've built a custom build that looks like it fixes this issue. Can you pull `mikenye/picard:fix_issue_2` and check if this fixed the problem for you?

It appears to work from me, and I've included a before and after pic below.

If this fixes your problem, I'll roll these changes into the master branch.

Cheers!

### Before
![ghibli-before](https://user-images.githubusercontent.com/6915079/76144618-360b0a00-60bd-11ea-85a3-b68732e0fbb4.png)

### After
![ghibli-after](https://user-images.githubusercontent.com/6915079/76144619-399e9100-60bd-11ea-85a9-47060d975141.png)

**Comment by kullervo610** [comment]
Thanks a lot looking into this. I pulled mikenye/picard:fix_issue_2 and made test with mixed results. Japanese font displaying works (I also see Japanese fonts both for fileanames and tags). 

However I experienced another issue (related?), when I try to look tag details of individual song (after I have matched a cluster with album using 'Scan') it do not show any tag information at bottom part of screen where this information is typically displayed. Secondly, it looks like that tag values are automatically saved without respecting 'Save' button. At least it shows automatically checkmark icon when matching happen with 'Scan'. Checkmark icon should only be show for files Picard has processed writing tags and rename, after I press 'Save' button over the album title line.

**Comment by mikenye** [comment]
Glad to hear the Japanese text issue is fixed. I'll hold off pushing the change through to the master branch in case this has caused your issues with tag information and/or saving. I'll try and replicate your problem to find out what's going on.

**Comment by kullervo610** [comment]
On parallel, I have been doing more tagging (=testing). Noticed some minor issues, probably unrelated to Japanese fonts issue reported here, I will let you know later on today my outcome when it comes my confidence level for Japanese font issues. It is great that you have test samples with that Studio Ghibli box, great movies and music by the way :), yourself where you can also test Japanese font issue.

**Comment by kullervo610** [comment]
Update ... I did quite extensive amount of tagging (=testing) and could not reproduce an issues I reported above i.e. "do not show any tag information at bottom part of screen". I had mix. of western and Japanese files and tags. Japanese fonts are shown and written nicely both to filenames and inside of of 'title' tags. From my perspective we are good and an issue reported here i.e. 'Japanese fonts not displayed correctly' is solved with mikenye/picard:fix_issue_2. Big thanks for your efforts and the fix!

**Comment by mikenye** [comment]
Excellent! Thanks for testing. I'll roll these changes into the master branch now.

**Comment by mikenye** [comment]
OK, changes have been rolled into the master branch. The image on hub.docker.com has been re-built and these changes will be in all images going forward. You should revert your container back to `mikenye/piaware:latest` now.

Thanks for reporting this issue and helping me test the fix. It is appreciated!
