### ISSUE TITLE
Using ReplayGain on .flac files fails

### ISSUE THREAD

**Issue by techie2000** [mikenye/docker-picard#21]
Looks like a missing dependency (probably flac itself)

**Comment by techie2000** [comment]
Trying to run metaflac from the command line fails.
Doing a find (in case it's not on a path) also returns no results.

I have installed flac from the command line, and then re-test ReplayGain on a .flac track....success

**Comment by mikenye** [comment]
Thanks so much for this. I've merged your PR and re-built the image. I appreciate your work on this!
