### ISSUE TITLE
Using ReplayGain plugin fails on certain file types

### ISSUE THREAD

**Issue by techie2000** [mikenye/docker-picard#23]
Extension of #19 but observed when trying to process OggVorbis, mp3 and wav format files.

The same solution can be used - install missing dependencies, in this case, vorbisgain, mp3gain, and wavpack (for wvgain).

However, mp3gain is no longer available on Ubuntu 'standard' installs as it was removed from upstream Debian. You have to (side)load from another repository :

```
add-apt-repository ppa:flexiondotorg/audio -y
apt-get update
apt-get install -y mp3gain
```

**Comment by mikenye** [comment]
You're a machine!
