### ISSUE TITLE
Missing library for internal player

### ISSUE THREAD

**Issue by techie2000** [mikenye/docker-picard#28]
On startup, the last entry written to the log is :
`W: 03:34:39,738 /usr/local/lib/python3.6/dist-packages/picard/ui/playertoolbar.__init__:106: Internal player: unavailable, libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory`

**Comment by techie2000** [comment]
I executed:

- Update the package index:`apt-get update`
- Install libpulse-mainloop-glib0 deb package:`apt-get install libpulse-mainloop-glib0`

and restarted.

This result in fresh error:
```
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
W: 13:25:30,590 /usr/local/lib/python3.6/dist-packages/picard/ui/playertoolbar.__init__:102: Internal player: unavailable, service is missing
```

So I execute `apt-get install libqt5multimedia5-plugins` and restarted, this time without errors in the log

**Comment by techie2000** [comment]
Whilst the errors are negated, the player does not play!

Not sure if this is relevant, but from the command line (inside the container)
```
root@fed7cb7b3b9d:/_music/Import# xdg-open test.mp3 
xdg-mime: mimetype argument missing
Try 'xdg-mime --help' for more information.
Error: no "view" mailcap rules found for type "audio/mpeg"
[1335:1335:1029/135349.290294:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: firefox: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium: not found
[1358:1358:1029/135349.325101:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: google-chrome: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'test.mp3'
```

**Comment by mikenye** [comment]
Hi @techie2000,

Once again, thanks for your efforts.

I can deploy a media player within the container, however how do you plan to get audio out? Are you passing through a sound device to the container?

**Comment by techie2000** [comment]
@mikenye I have no plans to use the internal player, so no biggy for me. I was actually trying to recreate another completely unrelated issue I've seen a couple of times when I noticed the #28 error in the log and took myself down this particular rabbit hole :)

I don't have log monitoring across my containers yet so I wasn't aware of the warning until now and manual investigation of the log. The fact that these libraries will be added means the warning will not happen and won't bug the c@&% out of me when I get around to systematic log monitoring!

Thanks once again for your speedy turnaround.

**Comment by techie2000** [comment]
For clarity, when I say "the player does not play!", I mean the Picard gui raises a warning at the foot of the screen rather than 'no sound heard'. The warning is "Internal player: The format of media resource isn't (fully) supported" This is for both .flac and .mp3 attempts.
That then generates docker log entries:
```
W: 14:13:49,157 /usr/local/lib/python3.6/dist-packages/picard/ui/mainwindow.set_statusbar_message:392: Internal player: The format of a media resource isn't (fully) supported
Warning: "No decoder available for type 'application/x-id3'."

W: 14:14:29,111 /usr/local/lib/python3.6/dist-packages/picard/ui/mainwindow.set_statusbar_message:392: Internal player: The format of a media resource isn't (fully) supported
Warning: "No decoder available for type 'audio/x-flac'."
```

**Comment by techie2000** [comment]
Executing `apt install gstreamer1.0-plugins-good` will sort it based on initial test.

**Comment by techie2000** [comment]
Whilst that resolved the warnings for the files I had previously tested with, I was still able to generate a similar error for another test:
```
W: 14:23:07,476 /usr/local/lib/python3.6/dist-packages/picard/ui/mainwindow.set_statusbar_message:392: Internal player: The format of a media resource isn't (fully) supported
Warning: "No decoder available for type 'video/x-h264, stream-format=(string)avc, alignment=(string)au, level=(string)3.1, profile=(string)main, codec_data=(buffer)014d401fffe1001b674d401fe8802802dd80b5010101400000fa40002ee003c60c448001000468ebef20, width=(int)1280, height=(int)720, framerate=(fraction)24000/1001, pixel-aspect-ratio=(fraction)1/1'."
```

Executing `apt install gstreamer1.0-libav ubuntu-restricted-extras` seemed to resolve that case (note, this brings down a load of dependencies). In addition, installation generates feedback:
```
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
```
but the waring in Picard gui/log is no longer appearing for the latest test case.

**Comment by mikenye** [comment]
How are you able to generate the "No decoder available for..." error?

I'm hesitant to install `ubuntu-restricted-extras` due to it increasing the size of the image from all the dependencies.

Looking at the `ubuntu-restricted-extras` package, I can see that it includes `libavcodec-extra`, which I'm hoping will provide the required codecs.

I'll add more packages - you should see a push/PR shortly, and `:latest` will be updated a few minutes later.

**Comment by mikenye** [comment]
Oh god I'm in dependency hell now

**Comment by mikenye** [comment]
OK I've added the following packages:

- gstreamer1.0-plugins-good
- gstreamer1.0-libav
- libpulse-mainloop-glib0
- libqt5multimedia5-plugins
- libavcodec57

Let me know how you go.

**Comment by techie2000** [comment]
I have tried my previous test cases (flac, mp3, m4a) and have not managed to generate any errors in the gui or in the (Docker) log *thumbs up*

**Comment by mikenye** [comment]
Thanks for the update and for your patience.
