### ISSUE TITLE
Opening more than a couple of modest Chromium tabs genrates error

### ISSUE THREAD

**Issue by techie2000** [mikenye/docker-picard#29]
It seems to depend on the size (kb)of the displayed pages, but generally, opening more than 4 tabs will cause the next tab not to display correctly (Error Code: 6), and generates Docker log :
```
[2014:2018:1101/171245.307850:ERROR:broker_posix.cc(46)] Received unexpected number of handles

[2014:2018:1101/171245.308472:ERROR:broker_posix.cc(46)] Received unexpected number of handles

[2014:2018:1101/171245.314057:ERROR:broker_posix.cc(46)] Received unexpected number of handles
```
I have noticed this behaviour on earlier releases too.

**Comment by mikenye** [comment]
Can you give `mikenye/picard:issue_29` a go and let me know if that fixes your issues?

**Comment by techie2000** [comment]
Installing it now. May take me a few hour before I can report back. Work stuff and family stuff happening today, getting in the good way of my stuff :(

**Comment by techie2000** [comment]
I've opened up 10 tabs (double what would previously cause issues) and much large and/or more memory intensive pages with graphics/videos, and seen no sign of the previously reported issue :)

**Comment by mikenye** [comment]
OK, changes have been merged and images rebuilt! Thanks.
