### ISSUE TITLE
CD drive access

### ISSUE THREAD

**Issue by phw** [mikenye/docker-picard#34]
Thanks a lot for this docker image. I just found out about it after having some user asking for help on the MB forums.

Gave this a try, and it really works great. One thing I could not get working is CD drive access. But I think it should be possible in theory. First I tried with `--device=/dev/sr0` docker argument, but this did not help.

But https://github.com/jlesage/docker-baseimage-gui/issues/3 indicates it would probably be sufficient to include the init script at https://github.com/jlesage/docker-handbrake/blob/master/rootfs/etc/cont-init.d/95-check-optical-drive.sh to get CD access working.

**Comment by mikenye** [comment]
Hi @phw, you're very welcome! Thanks to you and the rest of the Musicbrainz team for Picard and everything else you do!

I'll add the script and `lsscsi` to the image. I don't currently have access an optical drive to test this, so if you're able to test it would be appreciated.

If there's any other enhancements/additions/changes you feel would benefit the container, please don't hesitate to get in touch.

**Comment by mikenye** [comment]
The latest images on docker hub have been updated! Let me know how you fare. Thanks.

**Comment by phw** [comment]
Excellent, this works! You still need to add e.g. `--device=/dev/sr0` to the docker run command, but then with the new image version access to the CD drive is possible

**Comment by mikenye** [comment]
I'm glad that's working for you. Is there anything else I can do to improve the image?

**Comment by phw** [comment]
> Is there anything else I can do to improve the image?

Currently I have no further ideas :D

**Comment by cherryontopknife** [comment]
I'm not sure what I'm doing wrong, but I can't get this to work. My cdrom drive is mount at `/dev/sr0`, so I add that to the extra parameters in Docker. However, in Picard, I am unable to access the drive. The console throws 2 errors:

```
[app         ] E: 12:47:12,235 disc.read:70: Error while reading b'/dev/cdrom': cannot open device `/dev/cdrom'
[app         ] E: 12:47:15,038 disc.read:70: Error while reading b'/dev/sr0': cannot open device `/dev/sr0'
```
