### ISSUE TITLE
Album artwork missing / not possible to set

### ISSUE THREAD

**Issue by kullervo610** [mikenye/docker-picard#4]
When testing previous issue raised, I paid attention to behaviour where artwork is not available for an album, even it is present within Musicbrainz DB. Decided to wait new official build mikenye/picard:latest (pulled few minutes ago) to verify and unfortunatelly it is not possible to set artwork when tagging (visible for end userusers as '0 images', see below example). 

![Screen Shot 2020-03-09 at 18 22 49](https://user-images.githubusercontent.com/60269472/76240309-4d6c0380-6233-11ea-9409-ed9a07f1cc46.png)

Tried 2-3 albums and an issue is reprodusable.
Again BIG thanks bringing Picard for us as a container.

**Comment by mikenye** [comment]
Hello again! I've tried to reproduce this issue, and at this stage I don't think there's a problem with the container.

Looking at the [MusicBrainz documentation on cover art](https://musicbrainz.org/doc/Cover_Art ) they mention:

> As cover art has legal licensing and copyright issues associated, MusicBrainz can display cover art only from the Cover Art Archive, approved cover art sites

I've tried a couple of random albums and I can confirm that they are definitely getting cover artwork downloaded:

![tcq_midnight_marauders](https://user-images.githubusercontent.com/6915079/76272400-4fc37180-62b6-11ea-93ed-b33c7ba51607.png)

![tp_experience](https://user-images.githubusercontent.com/6915079/76272503-89947800-62b6-11ea-81bb-4c5a79840110.png)

Have you tried right-clicking on the album and checking to see if there are any "Other Versions" listed that do have artwork?

**Comment by kullervo610** [comment]
My bad, apologies. Your reply made me to recheck my settings for Cover art section, and I had missed to tickbox 'Cover Art Providers' to be used (see below). You are the most welcome to close this issue.

![Screen Shot 2020-03-10 at 11 07 00](https://user-images.githubusercontent.com/60269472/76302022-99fd2080-62bf-11ea-935b-d1fda26ac41b.png)

**Comment by mikenye** [comment]
No problems at all! :-)
