### ISSUE TITLE
:latest docker (c10e45172fe4) release means no web browser available

### ISSUE THREAD

**Issue by techie2000** [mikenye/docker-picard#42]
My system auto installed :latest (c10e45172fe4) docker version this morning. It appears to have broker the web-browser; Lookup in Browser search option, and Help/Help menu options fail to bring the web-browser up. I have forced 2.5.5 tag back on and normal service has been resumed.

**Comment by mikenye** [comment]
Hi @techie2000, I've hopefully fixed this.

Once the deployment finishes (https://github.com/mikenye/docker-picard/actions/runs/1157786412), please pull `:latest` and re-try.

Thanks.

**Comment by mikenye** [comment]
Action has finished, please test.

**Comment by techie2000** [comment]
All looks to be working again 👍

**Comment by mikenye** [comment]
Thanks!
