### ISSUE TITLE
AccousticBrainz feature - streaming_extractor_music

### ISSUE THREAD

**Issue by techie2000** [mikenye/docker-picard#49]
Is it possible to have this pre-installed? (https://acousticbrainz.org/download)

<img width="965" alt="image" src="https://user-images.githubusercontent.com/38585780/150213054-4208d9ec-d3d9-4d0e-b886-1756954ab9bb.png">

The extractor is only bundled with the Windows and MacOs Picard installer :( (https://picard-docs.musicbrainz.org/v2.7/en/config/options_acousticbrainz.html)

**Comment by mikenye** [comment]
Yes, i'll work on this, expect a PR shortly.

**Comment by mikenye** [comment]
This has been added to branch https://github.com/mikenye/docker-picard/tree/issue_48. The binary is located at: `/usr/local/sbin/streaming_extractor_music`.

**Comment by mikenye** [comment]
FYI - merged the PR, so I'm going to close this. :-)

**Comment by techie2000** [comment]
Seen to work well 👍  Thank-you very much for adding this
