### ISSUE TITLE
How to get Authorisation code within docker VNC page?

### ISSUE THREAD

**Issue by blade316** [mikenye/docker-picard#5]
I just installed this docker and its working really good.
I am loading it through IP:5900 in my browser
however because I can't launch a browser with the docker, I am unable to get the Authorization Code to log into MB, as it requires you to launch a browser and sign into your MB account to get the code.

![image](https://user-images.githubusercontent.com/19606551/79120256-d4ce0900-7dd5-11ea-8415-cdbe1e28c18a.png)

I have tried using the code from my other machine, but it doesn't work (obviously LOL)

Do you have any steps to be able to do this?

**Comment by mikenye** [comment]
After applying the fix for issue #7, this now appears to work correctly. Please let me know if this now works for you.

**Comment by blade316** [comment]
@mikenye thanks so much for the insanely quick response to this mate!
Ok so just updated to the :latest and yes its now opening firefox, allowing sig in and presenting the auth code, and it signs into MB

I am using VNC viewer as it gives a better experience over using VNC through the browser.

couple of minor things (no biggie if cant be fixed)

Firefox opens in fullscreen, so you have to close it to get back to Picard - not sure if it can run in windowed mode with standard maximize, minimize functions within a docker.
When you copy any text from firefox, its lost when you close it back to Picard - so just had to copy it to notepad on local machine first, then copy into Picard after.

As I said - very minor things :)

**Comment by mikenye** [comment]
I've added maximize/restore for all applications running within the container. Also, I've tested copy/paste and this seems to work OK now. You'll need to use `CTRL-C` / `CTRL-V` (not `⌘-C`/`⌘-V`.

**Comment by blade316** [comment]
@mikenye OK I'll test and report back

**Comment by blade316** [comment]
@mikenye OK confirming that restore and minimize is working, and copy and paste is working as long as you dont close firefox, otherwise it seems to clear the clipboard. So no biggie there.

**Comment by mikenye** [comment]
Awesome, thanks for the info. I'll close this one out.
