### ISSUE TITLE
Seach similar albums window unable to resize

### ISSUE THREAD

**Issue by blade316** [mikenye/docker-picard#6]
Not sure whats happening with this one, but when you right click and select the 'Search for similar albums' option, what normally happens is a window will appear and display results.

However in the docker (most likely something to do with lack of browser support), the window appears, but it doesn't display the results and can't be resized at all.

![image](https://user-images.githubusercontent.com/19606551/79120453-47d77f80-7dd6-11ea-86d6-2a179d3618c7.png)

Any ideas on how to resolve?

**Comment by blade316** [comment]
Update: I connected using VNC viewer and even though the window starts shrunk, I can resize when using VNC viewer

**Comment by mikenye** [comment]
I've just tried this after applying the fix for issue #7, and I can resize the window by using the small handle in the bottom-right corner of the window. Does this now work for you?

**Comment by blade316** [comment]
yeah I can resize now in both VNC through the browser, and also VNC viewer using the little handle in bottom right.

Not sure if its possible, but is there way to make the album search results window open in normal size like on normal machine? Any ideas why its opening all shrunk like it does?

**Comment by mikenye** [comment]
> Not sure if its possible, but is there way to make the album search results window open in normal size like on normal machine? Any ideas why its opening all shrunk like it does?

Yes, it's because I was starting picard with the `--no-restore` option for some reason. This is probably a hold over from an older version. I've removed this now and the windows open larger, and also will (hopefully) remember their size.

**Comment by blade316** [comment]
@mikenye  OK I'll test

**Comment by blade316** [comment]
@mikenye OK this part is working - great work bud :)

**Comment by mikenye** [comment]
Excellent! I'll close this one out.

Thanks for helping get this one resolved. I appreciate you reporting it and providing the info.
