### ISSUE TITLE
Browser Integration inside docker?

### ISSUE THREAD

**Issue by blade316** [mikenye/docker-picard#7]
It seems without the ability to load some sort of browser within the docker, browser integration is unable to work? I have tried in both VNC through a browser, and using VNC Viewer.

Is there any way around this?

**Comment by mikenye** [comment]
I've added Firefox into the container image. If you refresh your local copy of the image with `docker pull mikenye/picard:latest` and start your container again, browser integration should work.

Please report back and let me know if this works for you.

**Comment by blade316** [comment]
@mikenye  OK two different results on this one

If you right click a folder on the left and choose Lookup in Browser, 
![image](https://user-images.githubusercontent.com/19606551/79196836-1d3c0400-7e74-11ea-8ad8-d4de29b7c817.png)

Firefox opens and you can click the Tagger icon on the right to bring that item into Picard

![image](https://user-images.githubusercontent.com/19606551/79196953-4c527580-7e74-11ea-88f5-349ff6234265.png)

However if you right click an album on the right hand side, and select Lookup in Browser 
![image](https://user-images.githubusercontent.com/19606551/79197052-799f2380-7e74-11ea-9802-c26b20a2f173.png)

It opens Firefox and then crashes it every time

![image](https://user-images.githubusercontent.com/19606551/79196637-c5050200-7e73-11ea-8b0a-26c7d0f6c58a.png)

this is what shows in the docker container log file for that task:


14/04/2020 17:11:43 idle keyboard: turning X autorepeat back on.

14/04/2020 17:13:38 Got connection from client 127.0.0.1
14/04/2020 17:13:38 other clients:
14/04/2020 17:13:38 192.168.2.150
14/04/2020 17:13:38 Got 'ws' WebSockets handshake
14/04/2020 17:13:38 Got protocol: binary
14/04/2020 17:13:38 - webSocketsHandshake: using binary/raw encoding
14/04/2020 17:13:38 - WebSockets client version hybi-13

14/04/2020 17:13:38 incr accepted_client=2 for 127.0.0.1:42588 sock=11
14/04/2020 17:13:38 Client Protocol Version 3.8

14/04/2020 17:13:38 Protocol version sent 3.8, using 3.8

14/04/2020 17:13:38 rfbProcessClientSecurityType: executing handler for type 1
14/04/2020 17:13:38 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8

14/04/2020 17:13:39 Pixel format for client 127.0.0.1:
14/04/2020 17:13:39 32 bpp, depth 24, little endian
14/04/2020 17:13:39 true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
14/04/2020 17:13:39 no translation needed
14/04/2020 17:13:39 Enabling NewFBSize protocol extension for client 127.0.0.1
14/04/2020 17:13:39 Enabling full-color cursor updates for client 127.0.0.1
14/04/2020 17:13:39 Using image quality level 6 for client 127.0.0.1
14/04/2020 17:13:39 Using JPEG subsampling 0, Q79 for client 127.0.0.1
14/04/2020 17:13:39 Using compression level 9 for client 127.0.0.1
14/04/2020 17:13:39 Enabling LastRect protocol extension for client 127.0.0.1
14/04/2020 17:13:39 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)
14/04/2020 17:13:39 Using tight encoding for client 127.0.0.1
14/04/2020 17:13:39 client_set_net: 127.0.0.1 0.0001
14/04/2020 17:13:39 active keyboard: turning X autorepeat off.

14/04/2020 17:13:42 client 2 network rate 4336.1 KB/sec (153631.2 eff KB/sec)
14/04/2020 17:13:42 client 2 latency: 1.5 ms
14/04/2020 17:13:42 dt1: 0.0293, dt2: 0.0255 dt3: 0.0015 bytes: 234148
14/04/2020 17:13:42 link_rate: LR_BROADBAND - 1 ms, 110 KB/s
14/04/2020 17:18:39 idle keyboard: turning X autorepeat back on.

14/04/2020 17:18:49 active keyboard: turning X autorepeat off.


###!!! [Parent][MessageChannel] Error: (msgtype=0x370131,name=PContent::Msg_DetachBrowsingContext) Channel error: cannot send/recv



###!!! [Parent][MessageChannel] Error: (msgtype=0x370131,name=PContent::Msg_DetachBrowsingContext) Channel error: cannot send/recv



###!!! [Parent][MessageChannel] Error: (msgtype=0x370131,name=PContent::Msg_DetachBrowsingContext) Channel error: cannot send/recv



###!!! [Parent][MessageChannel] Error: (msgtype=0x370131,name=PContent::Msg_DetachBrowsingContext) Channel error: cannot send/recv



###!!! [Parent][MessageChannel] Error: (msgtype=0x370131,name=PContent::Msg_DetachBrowsingContext) Channel error: cannot send/recv



###!!! [Parent][MessageChannel] Error: (msgtype=0x370131,name=PContent::Msg_DetachBrowsingContext) Channel error: cannot send/recv

**Comment by mikenye** [comment]
Are you mapping the container's `/config` directory to persistent storage?

If so, could I trouble you to stop the container, delete the directory `.mozilla` from whereever you have `/config` mapped, and re-try the operation?

Are you able to try with an album with English song names etc? I'm wondering if maybe there's an issue with a missing font that provides the unicode symbols for the French unicode characters...

I haven't been able to replicate this issue locally.

**Comment by blade316** [comment]
@mikenye yes I am using persistent storage ... OK I didn't have a .mozilla folder in my /config mapping, this is the structure I have:

<img width="612" alt="Screen Shot 2020-04-14 at 6 45 10 pm" src="https://user-images.githubusercontent.com/19606551/79204648-3ba7fc80-7e80-11ea-8900-ce814588c82b.png">

So I removed the mozilla folder under xdg\cache and restarted the container.

Unfortunately this did not fix the issue.

I have also tried with multiple english only titles, but it crashes on all of them.

**Comment by mikenye** [comment]
With regards to the `.mozilla` folder - as it starts with a period, it likely won't show up in Finder. I'd suggest using Terminal. You should be able to see the `.mozilla` folder with `ls -la`.

**Comment by mikenye** [comment]
I've been doing some reading on the error:

`(msgtype=0x370131,name=PContent::Msg_DetachBrowsingContext) Channel error: cannot send/recv`

It looks like it could be related to:

- SELinux - is your docker host running SELinux?
- possibly a dbus issue
- Needing a reboot

So:

1. I've made a couple of minor changes, can you test the latest container?
1. Can you let me know if you're running SELinux?
1. Can you reboot and try again?

If none of these work, I'll put together a specific image for you with firefox's verbose logging turned on - maybe that will give us some more detail...

References:
- https://bugzilla.redhat.com/show_bug.cgi?id=1545844
- https://groups.google.com/forum/#!topic/zaproxy-users/tM2M4IuMpbc

**Comment by mikenye** [comment]
Apologies, didn't mean to close.

**Comment by blade316** [comment]
@mikenye OK regarding the mozilla folder, it showed up in terminal so i removed and restarted the container. Now here some new info ... I tested the right hand side 'Lookup in Browser' option, and if you leave Firefox in windowed mode, it works - I mean it takes way longer to load the page than using the left hand side 'Lookup in Browser' - but it loads.

However, as soon as I maximize the FireFox window it crashes. I am able to replicate this every time. The FireFox crash log shows this:

AdapterDeviceID: 0xffff
AdapterDriverVendor: mesa/llvmpipe
AdapterDriverVersion: 19.0.8.0
AdapterVendorID: 0xffff
Add-ons: doh-rollout%40mozilla.org:1.3.0,formautofill%40mozilla.org:1.0,screenshots%40mozilla.org:39.0.0,webcompat%40mozilla.org:9.0.0,default-theme%40mozilla.org:1.0,google%40search.mozilla.org:1.0,amazondotcom%40search.mozilla.org:1.1,bing%40search.mozilla.org:1.1,ddg%40search.mozilla.org:1.0,ebay%40search.mozilla.org:1.0,twitter%40search.mozilla.org:1.0,wikipedia%40search.mozilla.org:1.0
BuildID: 20200403170909
ContentSandboxCapabilities: 87
ContentSandboxCapable: 1
ContentSandboxLevel: 4
CrashTime: 1586866313
DOMIPCEnabled: 1
DesktopEnvironment: unknown
FramePoisonBase: 9223372036600930304
FramePoisonSize: 4096
InstallTime: 1586866184
IsWayland: 0
IsWaylandDRM: 0
Notes: Ubuntu 18.04.3 LTSFP(D00-L1000-W00000000-T000) WR? WR- OMTP? OMTP+4 
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: release
SafeMode: 0
StartupCrash: 0
StartupTime: 1586866254
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86-64","buildId":"20200403170909","version":"75.0","vendor":"Mozilla","displayVersion":"75.0","platformVersion":"75.0","xpcomAbi":"x86_64-gcc3","updaterAvailable":false},"partner":{"distributionId":"canonical","distributionVersion":"1.0","partnerId":"ubuntu","distributor":"canonical","distributorChannel":"ubuntu","partnerNames":["ubuntu"]},"system":{"memoryMB":24063,"virtualMaxMB":null,"cpu":{"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4_1","hasSSE4_2","hasAVX","hasAES"]},"os":{"name":"Linux","version":"4.19.107-Unraid","locale":"en-US"},"hdd":{"profile":{"model":null,"revision":null,"type":null},"binary":{"model":null,"revision":null,"type":null},"system":{"model":null,"revision":null,"type":null}},"gfx":{"D2DEnabled":null,"DWriteEnabled":null,"ContentBackend":"Skia","Headless":false,"adapters":[{"description":"llvmpipe (LLVM 8.0, 256 bits)","vendorID":"0xffff","deviceID":"0xffff","subsysID":null,"RAM":24063,"driver":null,"driverVendor":"mesa/llvmpipe","driverVersion":"19.0.8.0","driverDate":null,"GPUActive":true}],"monitors":[{"screenWidth":1920,"screenHeight":1080}],"features":{"compositor":"basic","gpuProcess":{"status":"unavailable"},"wrQualified":{"status":"denied"},"webrender":{"status":"opt-in"}}},"appleModelId":null},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":8,"telemetryEnabled":false,"locale":"en-US","intl":{"requestedLocales":["en-US"],"availableLocales":["en-US"],"appLocales":["en-US"],"systemLocales":["en-US"],"regionalPrefsLocales":["en-US"],"acceptLanguages":["en-US","en"]},"update":{"channel":"release","enabled":true,"autoDownload":false},"userPrefs":{"browser.search.widget.inNavBar":false,"browser.cache.disk.capacity":1048576},"sandbox":{"effectiveContentProcessLevel":4},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":false,"defaultSearchEngine":"google","defaultSearchEngineData":{"loadPath":"[distribution]/searchplugins/locale/en-US/google.xml","name":"Google","origin":"default","submissionURL":"https://www.google.com/search?client=ubuntu&channel=fs&q=&ie=utf-8&oe=utf-8"}},"profile":{"creationDate":18366,"firstUseDate":18366},"addons":{"activeAddons":{"doh-rollout@mozilla.org":{"version":"1.3.0","scope":1,"type":"extension","updateDay":18355,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Mozilla add-on that supports the roll-out of DoH","name":"DoH Roll-Out","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18355},"formautofill@mozilla.org":{"version":"1.0","scope":1,"type":"extension","updateDay":18355,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18355},"screenshots@mozilla.org":{"version":"39.0.0","scope":1,"type":"extension","updateDay":18355,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Take clips and screenshots from the Web and save them temporarily or permanently.","name":"Firefox Screenshots","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18355},"webcompat@mozilla.org":{"version":"9.0.0","scope":1,"type":"extension","updateDay":18355,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compat","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18355}},"theme":{"id":"default-theme@mozilla.org","blocklisted":false,"description":"A theme with the operating system color scheme.","name":"Default","userDisabled":false,"appDisabled":false,"version":"1.0","scope":4,"foreignInstall":false,"hasBinaryComponents":false,"installDay":18366,"updateDay":null},"activePlugins":[],"activeGMPlugins":{"gmp-gmpopenh264":{"version":"1.8.1.1","userDisabled":false,"applyBackgroundUpdates":1}}},"experiments":{"rollout-increasing-normandy-skew-out-changes-from-15-m-release-73-75-bug-1616898":{"branch":"active","type":"normandy-prefrollout","enrollmentId":"966a7cc3-ba6c-40a8-a7c8-abf17a1f93f2"}}}
ThreadIdNameMapping: 1420:"Gecko_IOThread",1429:"Timer",1430:"Netlink Monitor",1433:"Socket Thread",1440:"TRR Background",1444:"JS Watchdog",1445:"JS Helper",1446:"JS Helper",1447:"JS Helper",1448:"JS Helper",1449:"JS Helper",1450:"JS Helper",1451:"JS Helper",1452:"JS Helper",1454:"Cache2 I/O",1455:"Cookie",1457:"GMPThread",1458:"Worker Launcher",1459:"SoftwareVsyncThread",1460:"Compositor",1461:"ImgDecoder #1",1462:"ImageIO",1468:"ImageBridgeChild",1469:"IPDL Background",1470:"DOM Worker",1472:"QuotaManager IO",1473:"StreamTrans #3",1478:"StyleThread#1",1477:"StyleThread#0",1480:"StyleThread#3",1479:"StyleThread#2",1481:"StyleThread#4",1482:"StyleThread#5",1483:"Breakpad Server",1485:"IPC Launch",1488:"FS Broker 1486",1490:"ProcessHangMon",1516:"DataStorage",1517:"cert_storage",1518:"DNS Resolver #1",1519:"BackgroundThreadPool #1",1520:"Cache I/O",1521:"URL Classifier",1522:"HTML5 Parser",1523:"DNS Resolver #2",1524:"DOM Worker",1525:"localStorage DB",1528:"FS Broker 1526",1529:"DNS Resolver #3",1549:"mozStorage #1",1555:"DOM Worker",1556:"mozStorage #2",1557:"DOM Worker",1559:"DNS Resolver #4",1570:"DOM File",1574:"mozStorage #3",1586:"mozStorage #4",1589:"FS Broker 1587",1611:"SSL Cert #2",1612:"mozStorage #5",1618:"mozStorage #6",1623:"mozStorage #7",1649:"FS Broker 1647",1672:"IndexedDB #7",1680:"StreamTrans #6",
Throttleable: 1
URL: https://musicbrainz.org/release/80904885-0cf9-4051-9fd2-31f0eb5e9d93?tport=8000
UptimeTS: 59.94949334
Vendor: Mozilla
Version: 75.0
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed

Regarding the container, I am using UnRAID 6.8.3, docker version 19.03.5.

**Comment by blade316** [comment]
something I have also just noticed, it seems that if the URL contains the actual artist or release names, firefox doesn't crash - so if its ilke:

https://musicbrainz.org/taglookup?artist=Claude-Michel%20Sch%C3%B6nberg&release=Claude-Michel%20Sch%C3%B6nberg%20:%20Les%20chansons%20retrouv%C3%A9es&track=&tracknum=&duration=&filename=&tport=8000

then it seems to work properly

but if its like

https://musicbrainz.org/release/80904885-0cf9-4051-9fd2-31f0eb5e9d93?tport=8000

It only works in windowed mode - once you go to fullscreen it crashes.

Not sure if its related, but just something I noticed and can replicate everytime.

**Comment by mikenye** [comment]
OK, I've swapped `firefox` for `chromium-browser` running with `--no-sandbox`. I hope this  resolves your issue.

Pull `:latest` and give it a test.

Thanks for your perseverance!

**Comment by blade316** [comment]
@mikenye OK I have tested with the chromium update and the browser is no longer crashing, so it looks like we have success mate :)

I do have this message when chromium launches about --no-sandbox being unsupported - not sure if it matters for this though?

![image](https://user-images.githubusercontent.com/19606551/79277715-afccb980-7eed-11ea-9623-eea0e7f43b18.png)

**Comment by mikenye** [comment]
Yep, the `--no-sandbox` thing is unavoidable. Chromium won't start without it, unless we add special permissions to the container (`--cap-add=SYS_ADMIN`), which I want to avoid.

Ironically, the browser is already "sandboxed" given it is running as non-root inside a container anyway. :-)

**Comment by mikenye** [comment]
If you're happy, then I'll close this issue out.

**Comment by blade316** [comment]
@mikenye yeah mate happy to close it out - great success getting this container improved so quickly :) 

Side note: I installed the Musicbrainz Mirror container from Linuxserver.io team, as I thought it would be better and faster to have a local copy of db .... got it up and running, and when using Picard when you look up an album it says:

![image](https://user-images.githubusercontent.com/19606551/79288416-0516c400-7f0a-11ea-8f7f-c9abab5f1fc7.png)

So I click yes and it opens my local MB server, only to tell me it can't do it because its a Mirror Server

![image](https://user-images.githubusercontent.com/19606551/79288457-28417380-7f0a-11ea-84fe-64018bd17b2b.png)

I just can't win!! LOL

**Comment by mikenye** [comment]
Hmm that's interesting. I didn't know mirror server was a thing. Do you think it's worth trying to bundle that into the picard container?

**Comment by blade316** [comment]
@mikenye - No i think its best to keep it as a separate container to separate them in case something goes wrong with either one, they dont impact each other - as picard can always talk to live MB site.

This is the container - https://hub.docker.com/r/linuxserver/musicbrainz/

As I am using UnRAID though, I just installed it through the community apps plugin. (basically just a pretty gui to install and configure containers)

I even tried using the musicbrainz code from my online account that I used to set up the mirror, but it doesn't work. It seems there is probably no auth component written into the mirror version. Which sucks because it would AWESOME if you could have the same lookup functionality locally.

You can still manually use the 'Lookup in Browser' option with the mirror, but the 'Lookup' tool doesn't work :(

**Comment by mikenye** [comment]
Have you seen the official one?

https://github.com/metabrainz/musicbrainz-docker/tree/mbvm-38-dev

**Comment by blade316** [comment]
@mikenye no haven't seen that one - however just a quick scan, seems like its not a pre-built docker container, and you have to use a VM with docker installed, and then build it yourself? I've never done that before - I have only even used docker hub or unraid docker CA

**Comment by blade316** [comment]
also their DB is around 50GB whereas the docker I am using is only 5GB .... hmmmm I wonder what data mine is actually pulling down

**Comment by mikenye** [comment]
I think they're just running docker in a VM. But you wouldn't have to do that. You could for example build the image yourself using docker desktop, export it to a `tar` archive with `docker export`, move it to UnRAID and then use `docker load` to bring it into the local registry.

**Comment by mikenye** [comment]
I'm going to close this issue out, if you want to chat further about this stuff, ping me on Discord - my username is mikenye#4103 :)
