### ISSUE TITLE
Cannot display Korean characters

### ISSUE THREAD

**Issue by xxxarmitagexx** [mikenye/docker-picard#77]
Hi,

After installing the Picard container through docker compose: 

picard:
    image: mikenye/picard:latest
    container_name: picard
    environment:
      - ENABLE_CJK_FONT=1
      - TZ="Australia/Sydney"
    ports:
      - "5800:5800"
    volumes:
      - /srv/containers/picard:/config:rw
      - /media/external-drive/Music:/storage:rw

despite having the ENABLE_CJK_FONT environment variable set to 1, Korean characters are not displayed correctly.
Chinese/Japanese characters appears to display fine:

![image](https://github.com/mikenye/docker-picard/assets/94741683/89e5ddaa-04fb-428f-a2ee-c69dbf7c50fc)

What should be changed so that Korean characters are rendered properly?

**Comment by mikenye** [comment]
Hi @xxxarmitagexx,

Are you able to check if the problem still exists in version 2.10?

Thanks.

**Comment by xxxarmitagexx** [comment]
Hi,

Korean characters are now displaying correcting. 

After updating I am however facing a broader issue whereby none of the albums can be pulled due a SSL handshake issue: 

![image](https://github.com/mikenye/docker-picard/assets/94741683/f1daf635-0863-4d4e-a0e0-44191276f8ba)

Any idea what is causing the issue?
